export enum Technology {
  React = 'React.js',
  Redux = 'Redux',
  Node = 'Node.js',
  Sass = 'Sass',
  Express = 'Express',
  JavaScript = 'JavaScript',
  HTML = 'HTML',
  Chart = 'Chart.js',
  CSS = 'CSS',
  MongoDB = 'MongoDB',
  Python = 'Python',
  Flask = 'Flask',
  PostgreSQL = 'PostgreSQL',
  Axios = 'Axios',
  Heroku = 'Heroku',
  MapBox = 'MapBox',
  jQuery = 'jQuery',
  Webpack = 'Webpack',
  Yarn = 'Yarn',
  OpenWeatherAPI = 'OpenWeatherAPI',
  Ajax = 'Ajax',
  SQLAlchemy = 'SQLAlchemy',
  Marshmallow = 'Marshmallow',
  Bulma = 'Bulma',
  Mongoose = 'Mongoose'
}
